basePath: /
definitions:
  controllers.errorResponse:
    properties:
      error:
        type: string
    type: object
  controllers.jobLogResponse:
    properties:
      date:
        example: "2021-01-01"
        type: string
      job_name:
        example: upload movie
        type: string
      message:
        example: Uploading movie test.mp4
        type: string
    type: object
  controllers.uploadResponse:
    properties:
      count:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for the Media Indexer application
  title: Media Indexer API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - Ping
  /scan/job-name:
    get:
      description: Get the name of the last / current job
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Job Name
      tags:
      - Scan
  /scan/logs:
    get:
      description: Get the logs of the last / current job
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.jobLogResponse'
            type: array
      summary: Get Job Logs
      tags:
      - Scan
  /scan/movie:
    post:
      description: Scan movies from the configured folder
      produces:
      - application/json
      responses:
        "200":
          description: Scan started
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Scan Movies
      tags:
      - Scan
  /scan/tv:
    post:
      description: Scan TV Shows from the configured folder
      produces:
      - application/json
      responses:
        "200":
          description: Scan started
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Scan TV Shows
      tags:
      - Scan
  /upload/movie:
    post:
      consumes:
      - multipart/form-data
      description: Upload movies from the configured folder
      parameters:
      - description: Files to upload
        in: formData
        name: upload[]
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.uploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Upload Movies
      tags:
      - Upload
  /upload/tv:
    post:
      consumes:
      - multipart/form-data
      description: Upload TV Shows from the configured folder
      parameters:
      - description: Files to upload
        in: formData
        name: upload[]
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.uploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Upload TV Shows
      tags:
      - Upload
swagger: "2.0"
